# Questions 1:
# Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [2]:
import numpy as np
arr=np.arange(2,51,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


# Questions 2:
# Accept two lists of 5 elements each from the user.
# Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [4]:
ls1=[]
for i in range(5):
    x=int(input())
    ls1.append(x)
print(ls1)
print()

ls2=[]
for i in range(5):
    y=int(input())
    ls2.append(y)
print(ls2)
print()

arr1 = np.array(ls1)
arr2 = np.array(ls2)
arr3 = np.concatenate( (arr1,arr2) )
print(arr3)
print(np.sort(arr3))

5
9
8
7
2
[5, 9, 8, 7, 2]

0
3
1
45
98
[0, 3, 1, 45, 98]

[ 5  9  8  7  2  0  3  1 45 98]
[ 0  1  2  3  5  7  8  9 45 98]


# Questions 3:
# Write a code snippet to find the dimensions of a ndarray and its size.

In [5]:
a = np.array([[1,2,3,4],[2,3,4,5],[4,5,6,7],[6,7,8,9],[0,1,2,3]])
print("Number of dimensions",a.ndim)
print("The shape of the dimension",a.shape)
print("Size of array",a.size)

Number of dimensions 2
The shape of the dimension (5, 4)
Size of array 20


# Questions 4:

# How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
# Hint: np.newaxis, np.expand_dims

In [6]:
a_1d = np.array([9,8,7,6,5,4,3,2,1,0])
a_2d = a_1d[np.newaxis]
a2 = np.expand_dims(a_1d, axis=(1,-2,3))
a2.shape

print(a_1d)
print(a_1d.shape)
print()
print(a_2d)
print(a_2d.shape)

[9 8 7 6 5 4 3 2 1 0]
(10,)

[[9 8 7 6 5 4 3 2 1 0]]
(1, 10)


# Questions 5:
# Consider two square numpy arrays. Stack them vertically and horizontally.
# Hint: Use vstack(), hstack()

In [11]:
v = np.array([[78,87],[26,62],[12,21]])
h = np.array([[41,14],[63,36],[90,91]])

print("Vertical Stack")
print(np.vstack((v,h)))
print()
print("Horizontal Stack")
print(np.hstack((v,h)))

Vertical Stack
[[78 87]
 [26 62]
 [12 21]
 [41 14]
 [63 36]
 [90 91]]

Horizontal Stack
[[78 87 41 14]
 [26 62 63 36]
 [12 21 90 91]]


# Questions 6:
# How to get unique items and counts of unique items?

In [13]:
x = np.array([9,8,7,6,5,4,3,2,1,0,5,9,7,5,65,97,58,65,45,75,85,95,22,95,3])
unique, count = np.unique(x, return_counts = True)
print("Unique Items:",unique)
print("Unique Items Count:",count)

Unique Items: [ 0  1  2  3  4  5  6  7  8  9 22 45 58 65 75 85 95 97]
Unique Items Count: [1 1 1 2 1 3 1 2 1 2 1 1 1 2 1 1 2 1]
